-- CreateTable
CREATE TABLE "BhpRadiologi" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tanggal" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "pemakaian" TEXT NOT NULL,
    "harga" DECIMAL NOT NULL DEFAULT 0,
    "dev" DECIMAL NOT NULL DEFAULT 0,
    "fixer" DECIMAL NOT NULL DEFAULT 0,
    "film" DECIMAL NOT NULL DEFAULT 0,
    "amplopKertas" DECIMAL NOT NULL DEFAULT 0,
    "listrik" DECIMAL NOT NULL DEFAULT 0,
    "gajiKaryawan" DECIMAL NOT NULL DEFAULT 0,
    "kertasCetak" DECIMAL NOT NULL DEFAULT 0,
    "amplop" DECIMAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
